# Generated by Django 3.2.9 on 2021-11-24 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Value',
            new_name='ExchangeValue',
        ),
    ]
