# Generated by Django 3.2.9 on 2021-11-25 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0002_rename_value_exchangevalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangevalue',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'UDIS'), (1, 'USD'), (2, 'TIIE')], default=0),
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.SmallIntegerField(choices=[(0, 'UDIS'), (1, 'USD'), (2, 'TIIE')], default=0)),
                ('init_date', models.DateField()),
                ('end_date', models.DateField()),
                ('results', models.ManyToManyField(related_name='queries', to='cat.ExchangeValue')),
            ],
            options={
                'unique_together': {('type', 'init_date', 'end_date')},
            },
        ),
    ]
