# Generated by Django 3.2.9 on 2021-11-25 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0005_auto_20211124_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'UDIS'), (1, 'USD'), (2, 'TIIE 4 semanas'), (3, 'TIIE 13 semanas'), (4, 'TIIE 26 semanas')], default=0),
        ),
        migrations.AlterUniqueTogether(
            name='tiiesearch',
            unique_together={('init_date', 'end_date')},
        ),
    ]
