# Generated by Django 3.2.9 on 2021-11-26 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0006_auto_20211124_2044'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exchangevalue',
            options={'verbose_name': 'Exchange value', 'verbose_name_plural': 'Exchange values'},
        ),
        migrations.AlterModelOptions(
            name='search',
            options={'verbose_name': 'Search', 'verbose_name_plural': 'Searches'},
        ),
        migrations.AlterModelOptions(
            name='tiiesearch',
            options={'verbose_name': 'TIIE Search', 'verbose_name_plural': 'TIIE Searches'},
        ),
        migrations.AlterField(
            model_name='exchangevalue',
            name='date',
            field=models.DateField(verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='exchangevalue',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'UDIS'), (1, 'USD'), (2, 'TIIE 4 semanas'), (3, 'TIIE 13 semanas'), (4, 'TIIE 26 semanas')], default=0, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='exchangevalue',
            name='value',
            field=models.DecimalField(decimal_places=10, max_digits=15, verbose_name='value'),
        ),
        migrations.AlterField(
            model_name='search',
            name='avg_value',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True, verbose_name='avg value'),
        ),
        migrations.AlterField(
            model_name='search',
            name='end_date',
            field=models.DateField(verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='search',
            name='init_date',
            field=models.DateField(verbose_name='init date'),
        ),
        migrations.AlterField(
            model_name='search',
            name='max_value',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True, verbose_name='max value'),
        ),
        migrations.AlterField(
            model_name='search',
            name='min_value',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True, verbose_name='min value'),
        ),
        migrations.AlterField(
            model_name='search',
            name='results',
            field=models.ManyToManyField(related_name='queries', to='cat.ExchangeValue', verbose_name='results'),
        ),
        migrations.AlterField(
            model_name='search',
            name='tiie_search',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='searches', to='cat.tiiesearch', verbose_name='tiie search'),
        ),
        migrations.AlterField(
            model_name='search',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'UDIS'), (1, 'USD'), (2, 'TIIE 4 semanas'), (3, 'TIIE 13 semanas'), (4, 'TIIE 26 semanas')], default=0, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='tiiesearch',
            name='end_date',
            field=models.DateField(verbose_name='final date'),
        ),
        migrations.AlterField(
            model_name='tiiesearch',
            name='init_date',
            field=models.DateField(verbose_name='init date'),
        ),
    ]
