# Generated by Django 3.2.9 on 2021-11-26 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0007_auto_20211126_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='end_date',
            field=models.DateField(verbose_name='final date'),
        ),
    ]
