# Generated by Django 3.2.9 on 2021-11-26 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0008_alter_search_end_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='search',
            options={'verbose_name': 'Buscar', 'verbose_name_plural': 'Searches'},
        ),
        migrations.AlterField(
            model_name='exchangevalue',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'UDIS'), (1, 'USD'), (2, 'TIIE 4 weeks'), (3, 'TIIE 13 weeks'), (4, 'TIIE 26 weeks')], default=0, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='search',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'UDIS'), (1, 'USD'), (2, 'TIIE 4 weeks'), (3, 'TIIE 13 weeks'), (4, 'TIIE 26 weeks')], default=0, verbose_name='type'),
        ),
    ]
